name: 🚀 Deploy website on push
on:
  push:
    branches:
      - ci_test

jobs:
  web-deploy:
    name: 🎉 Deploy preview to cPanel
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: Use Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: 🔨 Build Project
        run: |
          npm install -g yarn
          yarn
          yarn generate

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.oqd.bcq.mybluehost.me
          username: gmltest@gml-test.themebuysell.com
          password: ${{ secrets.GML_TEST_PASS }}
          local-dir: ./dist/
